### ISSUE TITLE
[feature request] Rename image in EOM

### ISSUE THREAD

**Issue by Ubuntu-2020** [mate-desktop/eom#328] opened 2021-12-05 12:59 UTC
It will be good if in **EOM** it will be possible to rename the image when viewing the picture as in **Windows Photo Wiever**.
Rename image in in **Windows Live Photo Gallery**:
![Windows-Photo-Wiever](https://key.technospot.net/blogs/img/name-edit-vista.jpg)

**Comment by mbkma** [comment] 2021-12-05 13:52
duplicate of #115

**Closed by mbkma** 2021-12-05 13:52 UTC
