### ISSUE TITLE
Not displaying a large image and menu items going blank on mouseover

### ISSUE THREAD

**Issue by calluin** [mate-desktop/eom#88] opened 2015-07-10 13:46 UTC
I upgraded from Linux Mint x64 17.1 -> 17.2 (eom versions 1.8.1-0+rebecca -> 1.10.0-1+rafaela) and the new EOM fails to render a certain PNG image that was no problem before. The image appears as transparent. (see Screen1) After this failure, all other bitmaps show up the same way until eom is restarted. Also, menu items disappear after mouseover and toolbar buttons are left lighter after mouseover (see Screen2). When rescaling the image in GIMP, I found out that 9743x13775 resolution works fine, but 9744x13776 and larger causes the problem. When exporting to JPG, I get grey area instead of transparency.

For testing purposes, I am enclosing the image here: https://copy.com/cDBURchdea1yWvNo

![screen1](https://cloud.githubusercontent.com/assets/7095181/8619348/b68889cc-2716-11e5-8809-835d3eeb5b21.png)
![screen2](https://cloud.githubusercontent.com/assets/7095181/8619349/b9b018d6-2716-11e5-840a-82856990e3d0.jpg)

**Comment by monsta** [comment] 2015-08-28 10:56
I can reproduce it with 1.10.3, but not always. Sometimes the image is shown ok... sometimes it might disappear later if I switch (Alt-Tab) away and then back to eom... sometimes it's not shown at all right from the start. Anyway, in all cases the UI becomes horribly slow and has refreshing issues...

**Comment by calluin** [comment] 2015-08-29 12:53
I discovered that the issue is tied to a certain memory block allocation. It is also shared by other image viewers. I posted the information on MATE forums:
http://forums.mate-desktop.org/viewtopic.php?f=2&t=3722
Unfortunately, I am not Linux-savvy enough to know what's going on.

**Comment by calluin** [comment] 2016-04-04 09:59
Now I cannot reproduce it in eom, but gThumb and eog still have the issue. Is there a way to track down what helped and pass it to the developers of the other image viewers?

**Comment by raveit65** [comment] 2016-05-11 20:18
well, you can use 'git bisect' to find a commit which fix es the issue.
Normal this is used to find a regression which is caused by a commit, but it works also the other way around.

**Comment by raveit65** [comment] 2016-05-11 20:19
Do you agree with closing the issue?

**Comment by calluin** [comment] 2016-05-12 09:07
Yes, thank you.

**Closed** 2016-05-12 09:21 UTC
Labels: confirmed

**Comment by monsta** [comment] 2016-05-12 13:08
Well, I'm not really sure (because it was a crash fix, not a glitch fix), but it might be related to https://github.com/mate-desktop/eom/issues/93 being fixed in GTK+2 in Ubuntu 14.04, on which Mint 17.x versions are based.

As for GTK+3 (which eog and gthumb are using), I don't know if it has been patched. I only sent patches for GTK+2 because that's what eom is using.

**Comment by monsta** [comment] 2016-05-12 13:14
Ok, looks like the patch already was in GTK+ 3.10 (version of GTK+3 in Ubuntu 14.04) - it was committed even before that release. So the issue with eog and gthumb might be caused by something else.
