### ISSUE TITLE
multiple folders are all mixed up

### ISSUE THREAD

**Issue by pirate486743186** [mate-desktop/eom#296] opened 2021-01-06 17:16 UTC
#### Expected behaviour

When adding multiple folders (command line or drag and drop), the order of the files should follow the order of the folders.

for example:
1 2 3..... 1 2 3..... 1 2 3...

#### Actual behaviour

All files are mixed together in alphanumeric order.

for example:
1 1 1.... 2 2 2.... 3 3 3....

#### Steps to reproduce the behaviour

just drag and drop or open from cli, two folders with containing files with same names

#### MATE general version

I'm still using ubuntu 18.04
I don't think this matters.

**Comment by JorgeStolfi** [comment] 2021-08-30 00:31
See https://github.com/mate-desktop/eom/issues/308

**Comment by mbkma** [comment] 2021-08-30 07:37
duplicate of #308

**Closed by mbkma** 2021-08-30 07:37 UTC
