### ISSUE TITLE
Eom have a hard time displaying with high resolution images.

### ISSUE THREAD

**Issue by maandree** [mate-desktop/eom#105] opened 2015-09-27 12:42 UTC
EOM is really slow. It takes quite a while to open a 8000 × 8000 pixels PNG image, and zooming is a bit slow too.
https://www.nasa.gov/sites/default/files/thumbnails/image/crop_p_color2_enhanced_release.png 

Another file, a 30000 × 17078 pixels JPEG image, broke X when opening in EOM.
I had to SSH from another computer and not only kill EOM, I also had to kill X, and
then run startx from SSH to unblock the computer.

**Comment by raveit65** [comment] 2015-09-27 15:17
I can open that large image in 2 seconds from my disk.
I use a 4 ssds in raid10 mode at a hardware-raid controller.
Maybe your disk is a bit slow for such a large image?

**Comment by maandree** [comment] 2015-09-27 15:25
My disks can handle 71 MB just fine. (Takes only milliseconds)
And time does not decrease if I rencoding it to lossless JPEG
to reduce the size.
EOM is just slower than other software.

**Comment by raveit65** [comment] 2015-09-27 15:35
As i said , i can open your image fast with eom.

**Comment by maandree** [comment] 2015-09-27 15:40
Yay for you!

**Comment by monsta** [comment] 2015-09-29 12:28
First image opens in 3 seconds on my system (with plain hdd).

I don't see any links to the second image, but it looks similar to https://github.com/mate-desktop/eom/issues/93.

**Comment by maandree** [comment] 2015-09-29 14:06
Here it is the second image.

https://upload.wikimedia.org/wikipedia/commons/6/6d/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg

EOM cannot handle it. Dooble can, it just takes a few seconds of hard work.

**Comment by monsta** [comment] 2015-09-30 12:25
The second image made the whole desktop slow (probably due to swap usage), but eventually loaded and I was even able to see it. I had to quit eom though as the slowness continued. No crashes though (unlike in https://github.com/mate-desktop/eom/issues/93).

**Comment by raveit65** [comment] 2015-09-30 12:57
Same here with second image.
My box running out of memory and eom closed for this reason, but no crash and no alarm from fedora bug reporting tool (abrt).
....and same with eog.

**Comment by maandree** [comment] 2015-09-30 15:07
The image should take about 1,9 GB of RAM, so it does not need swap
if you have 6 GB to spare (or at least more than 2 GB). The kernel would
not swap out the filesystem cache, so there should be no page swapping.

**Comment by BangDroid** [comment] 2016-02-25 02:13
Confirming that EOM 1.12 is indeed having difficulty opening large images.

My reasoning is that I just upgraded from Linux Mint 17.2 (Mate 1.10) to Mint 17.3 (Mate 1.12) and I had no problems opening the same images with previous version, but with 1.12, many images simply do not load (blank black).

**Comment by monsta** [comment] 2016-02-25 08:29
Oh. So all was fine in 1.10...? :confused:

**Comment by BangDroid** [comment] 2016-02-26 17:29
As far as I can tell. A hole bunch of high-res images that I transferred over to 17.3 will now not load in EOM 1.12.
I double checked versions: Mint 17.2 =Mate 1.10, 17.3 =Mate 1.12

I am assuming this is the same issue. Though I haven't performed any debugging.

**Comment by monsta** [comment] 2016-04-04 08:32
Can you post these images somewhere so we could test them too?

Also - do you always get just the blank window? Do you also get slowdowns, or X server crashes, or maybe weird UI look described in #88?

**Comment by direwolfie** [comment] 2016-04-12 11:50
> EOM is really slow. It takes quite a while to open a 8000 × 8000 pixels PNG image, and zooming is a bit slow too.
> https://www.nasa.gov/sites/default/files/thumbnails/image/crop_p_color2_enhanced_release.png

Have the same issue. It does not crash but zoom in and out is extremely slow.
Tested on Linux Mint 17.3 and on Arch x86_64 (MATE v1.12.1; EOM v1.12.2).

**Comment by direwolfie** [comment] 2016-04-19 09:30
@maandree I have found a workaround for this issue. Go to Edit -> Preferences; and uncheck "Smooth images when zoomed-out". The picture will not look as good though when zoomed out.
There is also pretty high cpu usage (for an image viewer) when zooming in and out with this option enabled.
@monsta Should I open a new bug-report for this?

**Comment by monsta** [comment] 2016-05-12 14:09
Yes, zoom is a bit slow with that picture of the Earth. I'm not sure yet if it's related to this issue or not...

Have you guys tried eog (eye of gnome) BTW?

**Comment by raveit65** [comment] 2016-05-12 16:36
I can confirm that zoom in/out is much faster with eog and here those options are enabled.
- faster than eom with those option disabled
- much faster than eom with those option enabled.
An i see a higher CPU consumption if zoomed-out/in is used in a range < 100%
In this range zooming isn't really smooth.

**Comment by raveit65** [comment] 2016-05-12 16:56
Ok, problem with zooming < 100% is described here 
https://bugzilla.gnome.org/show_bug.cgi?id=665897, and fixes are in git, ie.
https://git.gnome.org/browse/eog/commit/?id=3d1859e321b9dea27e49bab9626044f3f5835420

**Comment by flexiondotorg** [comment] 2016-06-08 15:14
@raveit65 @monsta Please test https://github.com/flexiondotorg/eom/commit/2b418ef39094366cc6cbc3b856785ded39e189d1 and let me know if it solves the problem for you.

**Comment by flexiondotorg** [comment] 2016-06-08 15:36
My testing shows it fixes the issue.

**Comment by monsta** [comment] 2016-06-10 11:45
I've tested it on the mentioned image of Earth from NASA, and zoom is much faster now. Loading the image is still slow though... so @maandree and everyone, please test https://github.com/mate-desktop/eom/pull/126 and see if it makes things better for you.

**Comment by monsta** [comment] 2016-06-10 11:49
Works fine with http://public.media.smithsonianmag.com/legacy_blog/modis_wonderglobe_lrg.jpg as well.

**Closed** 2016-06-20 12:59 UTC
Labels: confirmed
