### ISSUE TITLE
Scrollbar does not move with large image

### ISSUE THREAD

**Issue by fredo-m** [mate-desktop/eom#132] opened 2016-11-18 18:13 UTC
Hi, 

With EOM 1.16.0-1 (Debian), I open a large image like a photo (larger than the EOM window) and I click the button to display it at its normal size. The horizontal and vertical scrollbars are in the middle. I can click on a scrollbar and move the mouse, the image moves but the scrollbar does not move, it remains in the middle.

Regards.

**Comment by thesquash** [comment] 2020-10-13 00:53
Sorry I'm so late to the party, but I'm pretty sure this is a GTK bug.  Here's why.

I've had this same issue since about the same time you have had it.  The dynamics of the issue are very weird.

Specifically, if you open a large image in EOM, then zoom it in *once* (for example, click "Normal size" or press "Zoom in" once), the scrollbars will refuse to respond.

Except only the slider will stick; the buttons are perfectly functional.

Also, this issue only appears on certain themes, including the Traditional family, the Submarine family and HighContrast.  (I mean HighContrast, not ContrastHigh, although that might also exhibit the behavior.)

I spent a weekend tracking down this issue and, after hours of cutting-and-pasting CSS code from themes that didn't exhibit the behavior, I discovered the code that "cures" it all:

    *:hover
    {
      -gtk-icon-effect: highlight;
    }

In English, for those unable to read CSS, that instructs GTK to "lighten" any image when you hover over it with the mouse pointer.  Strangely enough, applying this CSS immediately makes any of the themes work properly with EOM.  Replacing `highlight` with `darken` also does the trick, but no other modification I could think of worked, including removing the `:hover` pseudo-selector.

Zoom the image up more than once, or zoom it out even slightly without dismissing the scroll bars, and the issue disappears.  Temporarily, of course.  Zoom out until the scrollbars disappear, and then zoom in once, and the scrollbars get stuck again.  Unless you're using a theme with the "cure" applied.

For now, I'm still stumped.  Maybe the highlighting forces GTK to redraw all widgets more often, disabling some kind of CSS caching mechanism and thus causing scrollbars to jump to their proper positions?

**Comment by lukefromdc** [comment] 2020-10-13 02:37
Just confirmed this with current EOM 1.25 from git master (last pulled 9-18-2020). Interestingly, pulling the scrollbars with the mouse DOES move the image, it's just the scrollbars themselves that don't move. This is with gtk 3.24.21 installed

**Comment by thesquash** [comment] 2020-10-13 03:32
Sorry.  I didn't realize I had left out any important information.  Either way, just applied the template to my post.

**Comment by lukefromdc** [comment] 2020-10-13 03:38
Thanks. This is the first time I've seen this with any GTK3 application, so if GTK itself plays a role in this we must have hit a real corner case.

A possible kludge for this  (in the eom code) would be to apply a style class to the scrolled window with a highlight so faint as to be invisible, but it would be better to actually find and fix the problem.

**Comment by thesquash** [comment] 2020-10-13 03:43
Yeah.  I'll look into this more -- right here in my local time it's nearly midnight, so I'm going to call it quits for the night.

I'm surprised you responded so quickly to this issue, given that hardly anything's happened to it since it was posted nearly 4 years ago.

**Comment by thesquash** [comment] 2020-10-14 01:17
I'm not sure if this is just treatment of the symptoms, but I think I hit pretty close to pay dirt.

While going through my collection of screenshots using EOM earlier, I encountered this issue yet again, but then -- without applying CSS magic -- I opened a menu on the menu bar, then dismissed the menu.  Interestingly enough, the problem temporarily disappeared.  (Note:  Tooltips do not have any effect, nor does unfocusing and re-focusing the EOM window.)

Puzzled, I then resorted to the GTK+ Inspector again, first turning on the option to show whenever a widget is redrawn.  That turned up no strange behavior -- that is, the scrollbar regions were properly invalidated in both TraditionalOk and Menta.  Then I started viewing widget resizes, just out of curiosity -- and noticed that Menta triggered widget resizes on the entire window while scrolling, whereas TraditionalOk did not trigger any resizes.  Suspicious, I then checked the behavior of Pluma, an application which uses GtkScrolledWindow instead of discrete GtkScrollbars; being that GtkScrolledWindow is part of GTK, I figured the GTK developers would likely work around any GTK bugs or other issues in GtkScrolledWindow.  I discovered that widget resizes are issued to all elements, all the time while scrolling occurs in Pluma.

Returning to EOM, I opened the 'View' menu and then closed it, and scrolled again -- and I noticed that not only did the scrollbars work again, but also all widgets got sent the resize signal.  Odd!  I never found a line in GtkScrolledWindow which redraws everything no matter what, but I still suspect it's at least undocumented behavior in GTK.

To test my theory even further, I added this line to the very end of the `adjustment_changed_cb` function in the file `src/eom-scroll-view.c`:

    	gtk_widget_queue_resize (view);

This one line recalculates the size allocation to the EOM scroll view area (including the scrollbars) every time the area is scrolled.  This seems to work with all the themes and all the images I tried, and doesn't even slow down EOM significantly (I'm trying all this on an old 500 MHz Pentium III, so I probably should have noticed by now).

Maybe I'm misguided, but I thought that was rather interesting.

**Comment by lukefromdc** [comment] 2020-10-30 04:52
No surprise adding `gtk_widget_queue_resize (view);` to adjustment_changed_cb does not load down the CPU, this function is a callback that only runs when the "value changed" signal is emitted. Preparing a PR for this

**Comment by lukefromdc** [comment] 2020-10-30 04:54
Try
https://github.com/mate-desktop/eom/pull/283

**Comment by thesquash** [comment] 2020-10-30 19:28
I just tried it and wrote that I (with no official authority) approve of this change.  Thumbs up!

**Closed** 2020-11-03 05:51 UTC
Labels: confirmed
