### ISSUE TITLE
The images aren't rotated by eom

### ISSUE THREAD

**Issue by marmistrz** [mate-desktop/eom#54] opened 2014-07-08 17:14 UTC
Probably the same problem as described here, running eom 1.8.0

1. Open a .jpg photo
2. Rotate it
3. Exit eom and tell it to save it
Expected outcome: When the photo is opened once again, it's rotated
Actual outcome: The photo rotation doesn't change

Running Mint 17, latest as of 20140708

**Comment by monsta** [comment] 2015-01-01 09:32
Hmm, I can't reproduce it in Debian Testing with eom built from git master (1.9.x).

**Comment by monsta** [comment] 2015-01-01 09:34
@marmistrz: try it in Mint 17.1 Rebecca which has newer eom (1.8.1).

**Comment by monsta** [comment] 2015-10-02 11:19
Does it still happen in 1.10? If not I'll close this issue.

**Comment by ZrN-kAyDqY** [comment] 2015-10-24 05:40
It does not still happen 1.10.4.  Resolved.

**Closed** 2015-10-24 08:50 UTC
Labels: unconfirmed
